apiVersion: v1
kind: Pod
metadata:
  name: mynginxpod
spec:
  containers:
  - name: mynginxpod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - Port: 80
        containerPort: 30001
        
