apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc  
spec:
  replicas: 
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels: 
        app: myjavaapp
        version: 2.6.1        
    spec:
      containers:
        - name: mycontainer
          image: maha4iac/myonlinebooking:1
          ports:
            - containerPort: 8080